# Files for typos
# Instruction:  https://github.com/marketplace/actions/typos-action#getting-started

[default.extend-identifiers]

[default.extend-words]
als = "als"
THANN = "THANN"

[files]
extend-exclude = ["*.json*", "package-lock.json", "*.out.txt"]
